version: "3"

services:
  ubuntu-testing:
    container_name: ubuntu-testing
    build: 
      context: ../
      dockerfile: ./build/Ubuntu.dockerfile
    ports:
      - "9990:9990"
    volumes:
      - ../logs:/opt/app/logs
  
  client:
    container_name: client
    build: 
      context: ../
      dockerfile: ./build/Client.dockerfile
    volumes:
      - ../logs:/opt/app/logs
    depends_on:
      - ubuntu-testing