[app]
topPath = '/usr/bin/top'
iostatPath = '/usr/bin/iostat'
dfPath = '/bin/df'
tcpDumpPath = '/usr/sbin/tcpdump'
netStatPath = '/bin/netstat'

[metrics]
cpu = true
disks = true
network = true
connections = true

[grpc]
requestLogFile = './logs/grpc-requests.log'

[logg]
level = 'debug'